version: 2
project_name: domain-watch
before:
  hooks:
    - go mod download
    - go run ./internal/generate/completions
    - go run ./internal/generate/manpages --version={{ .Version }} --date={{ .CommitDate }}
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
archives:
  - formats: tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - LICENSE
      - README.md
      - manpages/*
      - completions/*
      - systemd/{{ .ProjectName }}.service
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
  groups:
    - title: Features
      order: 0
      regexp: "(feat)"
    - title: Fixes
      order: 1
      regexp: "(fix|perf)"
    - title: Dependencies
      order: 999
      regexp: "\\(deps\\):"
    - title: Others
      order: 998
brews:
  - homepage: https://github.com/gabe565/domain-watch
    description: Get notified about domain changes as they happen
    license: GPL-3.0
    repository:
      owner: gabe565
      name: homebrew-tap
    directory: Formula
    install: |
      bin.install "{{ .ProjectName }}"
      man1.install "manpages/{{ .ProjectName }}.1.gz"
      bash_completion.install "completions/{{ .ProjectName }}.bash" => "{{ .ProjectName }}"
      zsh_completion.install "completions/{{ .ProjectName }}.zsh" => "_{{ .ProjectName }}"
      fish_completion.install "completions/{{ .ProjectName }}.fish"
dockers:
  - &dockers
    image_templates:
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-amd64
    use: buildx
    dockerfile: goreleaser.Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - <<: *dockers
    image_templates:
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-armv6
    goarch: arm
    goarm: 6
    build_flag_templates:
      - "--platform=linux/arm/v6"
  - <<: *dockers
    image_templates:
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-armv7
    goarch: arm
    goarm: 7
    build_flag_templates:
      - "--platform=linux/arm/v7"
  - <<: *dockers
    image_templates:
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-arm64v8
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - &docker_manifests
    name_template: ghcr.io/gabe565/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-armv6
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-armv7
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - <<: *docker_manifests
    name_template: ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}
  - <<: *docker_manifests
    name_template: ghcr.io/gabe565/{{ .ProjectName }}:{{ .Major }}
  - <<: *docker_manifests
    name_template: ghcr.io/gabe565/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}
nfpms:
  - id: packages
    vendor: Gabe Cook
    homepage: https://github.com/gabe565/domain-watch
    description: Get notified about domain changes as they happen
    license: GPL-3.0
    maintainer: Gabe Cook <gabe565@gmail.com>
    formats:
      - deb
      - rpm
    contents:
      - src: ./manpages/{{ .ProjectName }}.1.gz
        dst: /usr/share/man/man1/{{ .ProjectName }}.1.gz
        file_info:
          mode: 0644
      - src: ./completions/{{ .ProjectName }}.bash
        dst: /usr/share/bash-completion/completions/{{ .ProjectName }}
        file_info:
          mode: 0644
      - src: ./completions/{{ .ProjectName }}.fish
        dst: /usr/share/fish/vendor_completions.d/{{ .ProjectName }}.fish
        file_info:
          mode: 0644
      - src: ./completions/{{ .ProjectName }}.zsh
        dst:  /usr/share/zsh/vendor-completions/_{{ .ProjectName }}
        file_info:
          mode: 0644
      - src: ./systemd/{{ .ProjectName }}.service
        dst: /usr/lib/systemd/system/{{ .ProjectName }}.service
        type: config
        packager: rpm
      - src: ./systemd/{{ .ProjectName }}.service
        dst: /lib/systemd/system/{{ .ProjectName }}.service
        type: config
        packager: deb
publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: |
      bash -c '
      if [[ "{{ .ArtifactName }}" != *.deb || "{{ .Arm }}" != 7 ]]; then
        curl -sf -Fpackage=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/gabe565/
      fi
      '
aurs:
  - name: "{{ .ProjectName }}-bin"
    homepage: https://github.com/gabe565/domain-watch
    description: Get notified about domain changes as they happen
    maintainers:
      - Gabe Cook <gabe565@gmail.com>
    license: GPL-3.0
    private_key: '{{ .Env.AUR_SSH_KEY }}'
    git_url: ssh://aur@aur.archlinux.org/{{ .ProjectName }}-bin.git
    skip_upload: auto
    package: |-
      # bin
      install -Dm755 "./{{ .ProjectName }}" "${pkgdir}/usr/bin/{{ .ProjectName }}"
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/{{ .ProjectName }}/LICENSE"
      # man page
      install -Dm644 "./manpages/{{ .ProjectName }}.1.gz" "${pkgdir}/usr/share/man/man1/{{ .ProjectName }}.1.gz"
      # completion
      install -Dm644 "./completions/{{ .ProjectName }}.bash" "${pkgdir}/usr/share/bash-completion/completions/{{ .ProjectName }}"
      install -Dm644 "./completions/{{ .ProjectName }}.zsh" "${pkgdir}/usr/share/zsh/site-functions/_{{ .ProjectName }}"
      install -Dm644 "./completions/{{ .ProjectName }}.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/{{ .ProjectName }}.fish"
      # systemd unit
      install -Dm644 "./systemd/{{ .ProjectName }}.service" "${pkgdir}/usr/lib/systemd/system/{{ .ProjectName }}.service"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
