repos:
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-mod-tidy-repo
      - id: go-fmt-repo
        args: [-w]
      - id: go-vet-mod
      - id: golangci-lint-mod
        args: [--fix]

  - repo: local
    hooks:
      - id: usage-docs
        name: usage-docs
        entry: go run ./internal/cmd/docs
        language: system
        files: ^(cmd|internal/cmd/docs)
        pass_filenames: false
