name: Docker Build

on:
  schedule:
    - cron: "0 7 * * 1"
  push:
    branches: master

env:
  image: ghcr.io/gabe565/domain-expiration-notifier

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute build variables
        id: vars
        run: |
          printf '::set-output name=short-sha::%s' "${GITHUB_SHA:0:7}"

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
          tags: |
            ${{ env.image }}:${{ steps.vars.outputs.short-sha }}
            ${{ env.image }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
